// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// print_times
void print_times(int nruns);
RcppExport SEXP _graphicalEvidence_print_times(SEXP nrunsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nruns(nrunsSEXP);
    print_times(nruns);
    return R_NilValue;
END_RCPP
}
// reset_times
void reset_times();
RcppExport SEXP _graphicalEvidence_reset_times() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    reset_times();
    return R_NilValue;
END_RCPP
}
// calc_eq_9
List calc_eq_9(NumericVector ones_vec, NumericVector one_indices, NumericVector post_mean_omega, NumericVector inv_sigma_stores, NumericVector mean_vecs, int p, int nmc);
RcppExport SEXP _graphicalEvidence_calc_eq_9(SEXP ones_vecSEXP, SEXP one_indicesSEXP, SEXP post_mean_omegaSEXP, SEXP inv_sigma_storesSEXP, SEXP mean_vecsSEXP, SEXP pSEXP, SEXP nmcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ones_vec(ones_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type one_indices(one_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type post_mean_omega(post_mean_omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inv_sigma_stores(inv_sigma_storesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean_vecs(mean_vecsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nmc(nmcSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_eq_9(ones_vec, one_indices, post_mean_omega, inv_sigma_stores, mean_vecs, p, nmc));
    return rcpp_result_gen;
END_RCPP
}
// set_cores
void set_cores(const int cores);
RcppExport SEXP _graphicalEvidence_set_cores(SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type cores(coresSEXP);
    set_cores(cores);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_graphicalEvidence_print_times", (DL_FUNC) &_graphicalEvidence_print_times, 1},
    {"_graphicalEvidence_reset_times", (DL_FUNC) &_graphicalEvidence_reset_times, 0},
    {"_graphicalEvidence_calc_eq_9", (DL_FUNC) &_graphicalEvidence_calc_eq_9, 7},
    {"_graphicalEvidence_set_cores", (DL_FUNC) &_graphicalEvidence_set_cores, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_graphicalEvidence(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
