
#########################################################################
# Temporary file only used for generating input parameters, not expected
# to be included in final package
#########################################################################

package_dir <- system.file(package = "graphicalEvidence")

# Read in pre existing matrices generated by MATLAB code
gen_params <- function() {
  g_mat <- file.path(
    package_dir, 'test_params', 'G_mat_q_5_n_10_delta_2.csv'
  )
  scale_mat <- file.path(
    package_dir, 'test_params', 'Scale_mat_q_5_n_10_delta_2.csv'
  )
  return(list(g_mat=gmat, scale_mat=scale_mat))
}
