# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

print_times <- function(nruns) {
    invisible(.Call(`_graphicalEvidence_print_times`, nruns))
}

reset_times <- function() {
    invisible(.Call(`_graphicalEvidence_reset_times`))
}

bind_random_samples <- function(rgammas, rnorms) {
    invisible(.Call(`_graphicalEvidence_bind_random_samples`, rgammas, rnorms))
}

mcmc_hw <- function(n, burnin, nmc, alpha, p, s_mat_nvec, scale_mat_nvec, g_mat_adj_nvec, gibbs_mat_nvec, init_gibbs_nvec) {
    .Call(`_graphicalEvidence_mcmc_hw`, n, burnin, nmc, alpha, p, s_mat_nvec, scale_mat_nvec, g_mat_adj_nvec, gibbs_mat_nvec, init_gibbs_nvec)
}

mcmc_last_col <- function(n, burnin, nmc, alpha, p, fixed_last_col_nvec, s_mat_nvec, scale_mat_nvec, g_mat_adj_nvec, gibbs_mat_nvec, post_mean_omega_nvec) {
    .Call(`_graphicalEvidence_mcmc_last_col`, n, burnin, nmc, alpha, p, fixed_last_col_nvec, s_mat_nvec, scale_mat_nvec, g_mat_adj_nvec, gibbs_mat_nvec, post_mean_omega_nvec)
}

set_cores <- function(cores) {
    invisible(.Call(`_graphicalEvidence_set_cores`, cores))
}

set_seed <- function(seed) {
    invisible(.Call(`_graphicalEvidence_set_seed`, seed))
}

