# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

print_times <- function(nruns) {
    invisible(.Call(`_graphicalEvidence_print_times`, nruns))
}

reset_times <- function() {
    invisible(.Call(`_graphicalEvidence_reset_times`))
}

calc_eq_9 <- function(ones_vec, one_indices, post_mean_omega, inv_sigma_stores, mean_vecs, p, nmc) {
    .Call(`_graphicalEvidence_calc_eq_9`, ones_vec, one_indices, post_mean_omega, inv_sigma_stores, mean_vecs, p, nmc)
}

set_cores <- function(cores) {
    invisible(.Call(`_graphicalEvidence_set_cores`, cores))
}

