
#########################################################################
# Temporary file only used for generating input parameters, not expected
# to be included in final package
#########################################################################

package_dir <- system.file(package = "graphicalEvidence")

# Read in pre existing matrices generated by MATLAB code
gen_params_G_Wishart <- function() {
  g_mat <- read.csv(file.path(
    package_dir, 'test_params', 'G_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)
  scale_mat <- read.csv(file.path(
    package_dir, 'test_params', 'Scale_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)
  S_mat <- read.csv(file.path(
    package_dir, 'test_params', 'S_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)
  X_mat <- read.csv(file.path(
    package_dir, 'test_params', 'X_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)
  
  return(list(X_mat=X_mat, g_mat=g_mat, S_mat=S_mat, scale_mat=scale_mat))
}

test_G_Wishart <- function() {
  
  # Get predetermined test inputs generated in MATLAB
  params <- gen_params_G_Wishart()
  
  print("Params are: ")
  print(params)
  
  # Make results repeatable
  set.seed(12345678)
  
  # Call top level function
  estimated_marginal <- evidence(
    xx=params$X_mat, S=params$S_mat, n=10, p=5, burnin=2e3, nmc=1e4,
    prior_name='G_Wishart', alpha=2, V=params$scale_mat, G=params$g_mat
  )
  
  cat(paste0("ans = ", estimated_marginal))
}
