
#########################################################################
# Temporary file only used for generating input parameters, not expected
# to be included in final package
#########################################################################

package_dir <- system.file(package = "graphicalEvidence")

# Read in pre existing matrices generated by MATLAB code
gen_params_G_Wishart <- function() {
  g_mat <- read.csv(file.path(
    package_dir, 'test_params', 'G_mat_q_5_n_10_delta_2_banded_param_1.csv'
  ), header=FALSE)
  scale_mat <- read.csv(file.path(
    package_dir, 'test_params', 'Scale_mat_q_5_n_10_delta_2_banded_param_1.csv'
  ), header=FALSE)
  S_mat <- read.csv(file.path(
    package_dir, 'test_params', 'S_mat_q_5_n_10_delta_2_banded_param_1.csv'
  ), header=FALSE)
  X_mat <- read.csv(file.path(
    package_dir, 'test_params', 'X_mat_q_5_n_10_delta_2_banded_param_1.csv'
  ), header=FALSE)
  
  return(list(X_mat=X_mat, g_mat=g_mat, S_mat=S_mat, scale_mat=scale_mat))
}

# Global env for tracking time usage of subsections of code
g_time_env <- new.env(parent=.GlobalEnv)
g_time_env$vec_log_normal_acc <- c()

test_G_Wishart <- function() {
  
  # Get predetermined test inputs generated in MATLAB
  params <- gen_params_G_Wishart()
  
  print("Params are: ")
  print(params)
  
  # Make results repeatable
  set.seed(12345678)
  
  # Sample size
  num_runs <- 5
  
  # Init store for estimated marginal repeated runs
  estimated_marginal_store <- numeric(num_runs)
  
  # Initialize compiled timers
  reset_times()
  
  # Save start in R program time
  our_time <- proc.time()
  
  # Subsection time profiling 
  g_time_env$vec_log_normal_calc_time <- 0
  
  # Call top level function
  for (i in 1:num_runs) {
    estimated_marginal_store[i] <- evidence(
      xx=params$X_mat, S=params$S_mat, n=10, p=5, burnin=2e3, nmc=1e4,
      prior_name='G_Wishart', alpha=2, V=params$scale_mat, G=params$g_mat
    )
  }
  
  # Cumulative execution time in R program
  cat('Execution time in R program (seconds):\n')
  print((proc.time() - our_time) / num_runs)
  
  # R program execution time for vec_log_normal_density
  cat("Time spend calculating vec_log_normal_density in R program (seconds)\n")
  print(g_time_env$vec_log_normal_calc_time / num_runs)
  
  # Compiled code time
  print_times(num_runs)
  
  # Estimated mean (sd)
  cat(paste0("ans = ", mean(estimated_marginal_store), " (", 
             sqrt(var(estimated_marginal_store)), ")"))

}
