
#########################################################################
# Temporary file only used for generating input parameters, not expected
# to be included in final package
#########################################################################

package_dir <- system.file(package = "graphicalEvidence")

# Read in pre existing matrices generated by MATLAB code
gen_params_G_Wishart <- function() {
  g_mat <- read.csv(file.path(
    package_dir, 'test_params', 'G_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)
  scale_mat <- read.csv(file.path(
    package_dir, 'test_params', 'Scale_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)
  X_mat <- read.csv(file.path(
    package_dir, 'test_params', 'X_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)
  return(list(
    X_mat=X_mat, g_mat=g_mat, scale_mat=scale_mat
  ))
}

# Read in pre existing matrices generated by MATLAB code
gen_params_BGL <- function() {
  X_mat <- read.csv(file.path(
    package_dir, 'test_params', 'X_mat_BGL_q_2_n_5_lambda_1.csv'
  ), header=FALSE)
  return(list(X_mat=X_mat))
}

# Read in pre existing matrices generated by MATLAB code
gen_params_GHS <- function() {
  X_mat <- read.csv(file.path(
    package_dir, 'test_params', 'X_mat_GHS_q_2_n_5_lambda_1.csv'
  ), header=FALSE)
  return(list(X_mat=X_mat))
}

gen_params_Wishart <- function() {
  X_mat <- read.csv(file.path(
    package_dir, 'test_params', 'X_mat_Wishart_q_5_n_10_alpha_7.csv'
  ), header=FALSE)
  scale_mat <- read.csv(file.path(
    package_dir, 'test_params', 'Scale_mat_q_5_n_10_alpha_7.csv'
  ), header=FALSE)
  return(list(X_mat=X_mat, scale_mat=scale_mat))
}

# Global env for tracking time usage of subsections of code
g_time_env <- new.env(parent=.GlobalEnv)

test_sampling_G_Wishart <- function(num_samples) {
  
  g_mat <- read.csv(file.path(
    package_dir, 'test_params', 'G_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)
  scale_mat <- read.csv(file.path(
    package_dir, 'test_params', 'Scale_mat_q_5_n_10_delta_2.csv'
  ), header=FALSE)

  # Save start in R program time
  our_time <- proc.time()

  ref_res <- prior_sampling_G_Wishart(
    5, num_samples / 2, num_samples / 2, g_mat, scale_mat, 2
  )
  cat('For p=5 (',num_samples,  ' samples ): interpreted time (seconds):\n')
  print((proc.time() - our_time))

  # Save start in R program time
  our_time <- proc.time()

  res <- prior_sampling(
    5, 0, num_samples / 2, 'G_Wishart', seed=42, G_mat_adj=g_mat,
    scale_matrix=scale_mat, alpha=2
  )

  # Cumulative execution time in R program
  cat('For p=5 (',num_samples,  ' samples ): execution time in R program (seconds):\n')
  print((proc.time() - our_time))

  print("means")
  print(apply(res, c(1, 2), mean))
  print(apply(ref_res, c(1, 2), mean))
  
  g_mat <- read.csv(file.path(
    package_dir, 'test_params', 'G_mat_q_50_n_100_delta_15.csv'
  ), header=FALSE)
  scale_mat <- read.csv(file.path(
    package_dir, 'test_params', 'Scale_mat_q_50_n_100_delta_15.csv'
  ), header=FALSE)

  # Save start in R program time
  our_time <- proc.time()

  res <- graphicalEvidence::prior_sampling(
    50, num_samples / 2, num_samples / 2, 'G_Wishart', seed=42,
    G_mat_adj=g_mat, scale_matrix=scale_mat, alpha=15
  )

  # Cumulative execution time in R program
  cat('For p=50 (',num_samples,  ' samples ): execution time in R program (seconds):\n')
  print((proc.time() - our_time))

  
  g_mat <- read.csv(file.path(
    package_dir, 'test_params', 'G_mat_q_100_n_200_delta_50.csv'
  ), header=FALSE)
  scale_mat <- read.csv(file.path(
    package_dir, 'test_params', 'Scale_mat_q_100_n_200_delta_50.csv'
  ), header=FALSE)
  
  # Save start in R program time
  our_time <- proc.time()

  res <- prior_sampling(
    100, num_samples / 2, num_samples / 2, 'G_Wishart', seed=42,
    G_mat_adj=g_mat, scale_matrix=scale_mat, alpha=50
  )

  # Cumulative execution time in R program
  cat('For p=100 (',num_samples,  ' samples ): execution time in R program (seconds):\n')
  print((proc.time() - our_time))

}

test_G_Wishart <- function(num_runs) {
  
  # Get predetermined test inputs generated in MATLAB
  params <- gen_params_G_Wishart()
  
  print("Params are: ")
  print(params)
  
  # Make results repeatable
  rs_seed <- 123456789
  set.seed(rs_seed)
  set_seed(rs_seed)
  
  # Initialize compiled timers
  reset_times()
  
  # Save start in R program time
  our_time <- proc.time()
  
  # Subsection time profiling 
  g_time_env$vec_log_normal_calc_time <- 0
  g_time_env$mcmc_hw_calc_time <- 0
  g_time_env$vec_log_gamma_calc_time <- 0
  g_time_env$mcmc_last_col_calc_time <- 0
  
  # Call top level function
  estimated_marginal_store <- evidence(
    xx=params$X_mat, burnin=2e3, nmc=1e4, prior_name='G_Wishart', 
    runs=num_runs, alpha=2, V=params$scale_mat, G=params$g_mat,
    print_progress=FALSE
  )
  
  # Cumulative execution time in R program
  cat('Execution time in R program (seconds):\n')
  print((proc.time() - our_time) / num_runs)
  
  # R program execution time for Hao Wang MCMC sampling (unrestricted)
  cat("Time spend in unrestricted Hao Wang MCMC in R program (seconds)\n")
  print(g_time_env$mcmc_hw_calc_time / num_runs)
  
  # R program execution time for vec_log_normal_density
  cat("Time spend calculating vec_log_normal_density in R program (seconds)\n")
  print(g_time_env$vec_log_normal_calc_time / num_runs)
  
  # R program execution time for Hao Wang MCMC sampling (unrestricted)
  cat("Time spend in last col MCMC in R program (seconds)\n")
  print(g_time_env$mcmc_last_col_calc_time / num_runs)
  
  # R program execution time for vec_log_normal_density
  cat("Time spend calculating vec_log_gamma_density in R program (seconds)\n")
  print(g_time_env$vec_log_gamma_calc_time / num_runs)
  
  # Compiled code time
  print_times(num_runs)
  
  # Estimated mean (sd)
  cat(paste0("ans = ", estimated_marginal_store$mean, " (", 
             estimated_marginal_store$sd, ")\n"))

  hist(estimated_marginal_store$results, breaks=40)
  return(estimated_marginal_store)
}

test_BGL <- function(num_runs) {
  
  # Get predetermined test inputs generated in MATLAB
  params <- gen_params_BGL()
  
  print("Params are: ")
  print(params)
  
  # Make results repeatable
  rs_seed <- 12345678
  set.seed(rs_seed)
  set_seed(rs_seed)
  
  # Initialize compiled timers
  reset_times()
  
  # Save start in R program time
  our_time <- proc.time()
  
  # Subsection time profiling 
  g_time_env$vec_log_normal_calc_time <- 0
  g_time_env$mcmc_hw_calc_time <- 0
  g_time_env$vec_log_gamma_calc_time <- 0
  g_time_env$mcmc_last_col_calc_time <- 0
  
  # Call top level function
  estimated_marginal_store <- evidence(
    xx=params$X_mat, burnin=1e3, nmc=5e3, prior_name='BGL', 
    runs=num_runs, lambda=1
  )
  
  # Cumulative execution time in R program
  cat('Execution time in R program (seconds):\n')
  print((proc.time() - our_time) / num_runs)
  
  # R program execution time for Hao Wang MCMC sampling (unrestricted)
  cat("Time spend in unrestricted Hao Wang MCMC in R program (seconds)\n")
  print(g_time_env$mcmc_hw_calc_time / num_runs)
  
  # R program execution time for Hao Wang MCMC sampling (unrestricted)
  cat("Time spend in last col MCMC in R program (seconds)\n")
  print(g_time_env$mcmc_last_col_calc_time / num_runs)
  
  # Compiled code time
  print_times(num_runs)
  
  # Estimated mean (sd)
  cat(paste0("ans = ", estimated_marginal_store$mean, " (", 
             estimated_marginal_store$sd, ")\n"))
  
  hist(estimated_marginal_store$results, breaks=40)
  return(estimated_marginal_store)
}

test_GHS <- function(num_runs) {
  
  # Get predetermined test inputs generated in MATLAB
  params <- gen_params_GHS()
  
  print("Params are: ")
  print(params)
  
  # Make results repeatable
  rs_seed <- 12345678
  set.seed(rs_seed)
  set_seed(rs_seed)
  
  # Initialize compiled timers
  reset_times()
  
  # Save start in R program time
  our_time <- proc.time()
  
  # Subsection time profiling 
  g_time_env$vec_log_normal_calc_time <- 0
  g_time_env$mcmc_hw_calc_time <- 0
  g_time_env$vec_log_gamma_calc_time <- 0
  g_time_env$mcmc_last_col_calc_time <- 0
  
  # Call top level function
  estimated_marginal_store <- evidence(
    xx=params$X_mat, burnin=1e3, nmc=5e3, prior_name='GHS', 
    runs=num_runs, lambda=1
  )
  
  # Cumulative execution time in R program
  cat('Execution time in R program (seconds):\n')
  print((proc.time() - our_time) / num_runs)
  
  # R program execution time for Hao Wang MCMC sampling (unrestricted)
  cat("Time spend in unrestricted Hao Wang MCMC in R program (seconds)\n")
  print(g_time_env$mcmc_hw_calc_time / num_runs)
  
  # R program execution time for Hao Wang MCMC sampling (unrestricted)
  cat("Time spend in last col MCMC in R program (seconds)\n")
  print(g_time_env$mcmc_last_col_calc_time / num_runs)
  
  # Compiled code time
  print_times(num_runs)
  
  # Estimated mean (sd)
  cat(paste0("ans = ", estimated_marginal_store$mean, " (", 
             estimated_marginal_store$sd, ")\n"))
  
  hist(estimated_marginal_store$results, breaks=40)
  return(estimated_marginal_store)
}

test_Wishart <- function(num_runs) {
  
  # Get predetermined test inputs generated in MATLAB
  params <- gen_params_Wishart()
  
  print("Params are: ")
  print(params)
  
  # Make results repeatable
  rs_seed <- 12345678
  set.seed(rs_seed)
  set_seed(rs_seed)
  
  # Initialize compiled timers
  # reset_times()
  
  # Save start in R program time
  our_time <- proc.time()
  
  # Subsection time profiling 
  # g_time_env$vec_log_normal_calc_time <- 0
  # g_time_env$mcmc_hw_calc_time <- 0
  # g_time_env$vec_log_gamma_calc_time <- 0
  # g_time_env$mcmc_last_col_calc_time <- 0
  
  # Call top level function
  estimated_marginal_store <- evidence(
    xx=params$X_mat, burnin=1e3, nmc=5e3, prior_name='Wishart', 
    runs=num_runs, alpha=7, V=params$scale_mat,
  )
  
  # Estimated mean (sd)
  cat(paste0("ans = ", estimated_marginal_store$mean, " (", 
             estimated_marginal_store$sd, ")\n"))
  
  hist(estimated_marginal_store$results, breaks=40)
  return(estimated_marginal_store)
}

